<?php

/**
 * $country places/cities/municipalities/districts
 * - $count places/cities/municipalities/districts
 * 
 * Source: 
 * - [Please add the source(s) link(s) to check the list of places]
 * 
 * @author  Your Name Here <yourname@here.com> | https://yourwebsite.com
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

// Replace 'XX' code for your Country Code. E.g. 'NG' for Nigeria, 'CO' for Colombia, 'VE' for Venezuela, etc.
// Please refer to WooCommerce country codes : https://github.com/woocommerce/woocommerce/blob/master/i18n/countries.php
$places['BO'] = array(
  // Replace 'AA' code with the code of the State you want to mapping this places  
  'BO-B' => array(
    'Trinidad',
    'Riberalta',
    'Guayaramerin',
    'San Borja',
    'Santa Ana del Yacuma',
    'San Ignacio de Moxos',
    'Rurrenabaque',
    'Magdalena',
    'Santa Rosa de Yacuma',
    'San Joaquín',
    'Exaltación',
    'Baures',
    'San Javier',
    'San Ramón',
    'Huacaraje',
    'Loreto',
    'Puerto Siles',
  ),
  'BO-C' => array(
    'Sucre',
    'San Lucas',
    'Monteagudo',
    'Culpina',
    'Poroma',
    'Trabuco',
    'Villa Charcas',
    'Camargo',
    'Tarvita',
    'Incahuasi',
    'Presto',
    'Zudañes',
    'Villa Serrano',
    'Azurduy',
    'Padilla',
    'Yamparáez',
    'Muyupampa',
    'Yotala',
    'Tomina',
    'Huacareta',
    'Mojocoya',
    'Ida',
    'Macharetí',
    'Sopachuy',
    'Villa Alcalá',
    'El Villar',
    'Las Carreras',
    'Villa Abecia',
    'Huacaya',
  ),
  'BO-H' => array(
'Cochabamba',
'Sacaba',
'Quillacollo',
'Villa Tunari',
'Tiquipaya',
'Colcapirhua',
'Vinto',
'Puerto Villaroel',
'Sipe Sipe',
'Entre Ríos',
'Punata',
'Mizque',
'Tapacari',
'Independencia',
'Aiquile',
'Cliza',
'Chimoré',
'Tiraque',
'Shinahota',
'Colomi',
'Capinota',
'Cocapata',
'Arbieto',
'Totora',
'San Benito',
'Morochata',
'Pocona',
'Arque',
'Tacopaya',
'Pojo',
'Arani',
'Vacas',
'Tarata',
'Villa Rivero',
'Bolívar',
'Anzaldo',
'Toco',
'Pasorapa',
'Santiváñez',
'Omereque',
'Tolata',
'Vila Vila',
'Sacabamba',
'Sicaya',
'Alalay',
'Cuchumuela',
'Tacachi',
  ),
  'BO-L' => array(
    'El Alto',
    'La Paz',
    'Viacha',
    'Caranavi',
    'Achacachi',
    'La Asunta',
    'Sica Sica',
    'Pucarani',
    'Palos Blancos',
    'Laja',
    'Sorata',
    'Patacamaya',
    'Achocalla',
    'Apolo',
    'Colquiri',
    'Coroico',
    'Chulumani',
    'Batallas',
    'Irupana',
    'Coripata',
    'Palca',
    'Mecapaca',
    'Mocomoco',
    'Jesús de Machaca',
    'Copacabana',
    'Guanay',
    'Inquisivi',
    'Caquiaviri',
    'Carabuco',
    'Mapiri',
    'Ancoraimes',
    'Charazani',
    'Sapahaqui',
    'Calamarca',
    'Tiahuanacu',
    'Chuma',
    'Cairoma',
    'Puerto Acosta',
    'Alto Beni',
    'Luribay',
    'Corocoro',
    'Cajuata',
    'Tipuani',
    'Calacoto',
    'Colquencha',
    'Ixiamas',
    'Teoponte',
    'Umala',
    'San Pedro de Curahuara',
    'San Buenaventura',
    'Santiago de Huata',
    'Ayata',
    'Quime',
    'Tacacoma',
    'Puerto Pérez',
    'Huarina',
    'Ichoca',
    'Ayo Ayo',
    'Yaco',
    'Callapa',
    'Guaqui',
    'Escoma',
    'Papel Pampa',
    'Desaguadero',
    'Pelechuco',
    'Taraco',
    'Yanacachi',
    'Tito Yupanqui',
    'San Andrés de Machaca',
    'San Pedro de Tiquina',
    'Aucapata',
    'Villa Libertad Licoma',
    'Humanata',
    'Malla',
    'Waldo Ballivián',
    'Collana',
    'Chua Cocani',
    'Santiago de Machaca',
    'Huatajata',
    'Comanche',
    'Combaya',
    'Curva',
    'Charaña',
    'Catacora',
    'Quiabaya',
    'Chacarilla',
    'Nazacara de Pacajes',
  ),
  'BO-N' => array(
'Ciudad de Oruro',
'Belén de Andamarca',
'Caracollo',
'Carangas',
'Challapata',
'Chipaya',
'Choquecota',
'Coipasa',
'Corque',
'Cruz de Machacamarca',
'Curahuara de Carangas',
'El Choro',
'Escara',
'Esmeralda',
'Eucaliptus',
'Huachacalla',
'Huanuni',
'Huayllamarca',
'La Rivera',
'Machacamarca',
'Pampa Aullagas',
'Paria',
'Pazña',
'Pisiga',
'Poopó',
'Sabaya',
'Salinas de Garci Mendoza',
'Santiago de Andamarca',
'Santiago de Huari',
'Santuario de Quillacas',
'Todos Santos',
'Toledo',
'Totora',
'Turco',
'Yunguyo de Litoral',
  ),
  'BO-O' => array(
'Bella Flor',
'Bolpebra',
'Cobija',
'Filadelfia',
'Ingavi',
'Nueva Esperanza',
'Porvenir',
'Puerto Gonzalo Moreno',
'Puerto Rico',
'San Lorenzo',
'San Pedro',
'Santa Rosa del Abuná',
'Santos Mercado',
'Sena',
'Villa Nueva',
  ),
  'BO-P' => array(
'Acasio',
'Arampampa',
'Atocha',
'Betanzos',
'Caiza D',
'Caripuyo',
'Chaquí',
'Chuquihuta',
'Ckochas',
'Colcha K',
'Colquechaca',
'Llallagua',
'Llica',
'Mojinete',
'Ocurí',
'Pocoata',
'Porco',
'Potosí Ciudad',
'Puna',
'Ravelo',
'Sacaca',
'San Agustín',
'San Antonio de Esmoruco',
'San Pablo de Lípez',
'San Pedro de Buena Vista',
'San Pedro de Macha',
'San Pedro de Quemes',
'Santiago de Cotagaita',
'Tacobamba',
'Tahua',
'Tinguipaya',
'Tomave',
'Toro Toro',
'Tupiza',
'Uncía',
'Urmiri',
'Uyuni',
'Villazón',
'Vitichi',
'Yocalla',
  ),
  'BO-S' => array(
'Ascensión de Guarayos',
'Boyuibe',
'Buena Vista',
'Cabezas',
'Camiri',
'Charagua',
'Colpa Bélgica',
'Comarapa',
'Concepción',
'Cotoca',
'Cuatro Cañadas',
'Cuevo',
'El Carmen Rivero Tórrez',
'El Puente',
'El Trigal',
'Fernández Alonso',
'General Saavedra',
'Gutiérrez (Bolivia)',
'La Guardia (Bolivia)',
'Lagunillas (Bolivia)',
'Mairana',
'Mineros (Bolivia)',
'Montero',
'Okinawa Uno',
'Pailón',
'Pampagrande',
'Portachuelo',
'Postrervalle',
'Puerto Quijarro',
'Puerto Suárez',
'Quirusillas',
'Roboré',
'Saipina',
'Samaipata',
'San Antonio de Lomerío',
'San Carlos',
'San Ignacio de Velasco',
'San Javier',
'San José de Chiquitos',
'San Juan de Yapacaní',
'San Julián',
'San Matías',
'San Matías',
'San Miguel de Velasco',
'San Pedro',
'San Rafael de Velasco',
'San Ramón',
'Santa Cruz de la Sierra',
'Santa Rosa del Sara',
'Urubichá',
'Warnes',
  ),
  'BO-T' => array(
'Bermejo',
'Caraparí',
'El Puente',
'Entre Ríos',
'Padcaya',
'San Lorenzo',
'Tarija Ciudad',
'Uriondo',
'Villa Montes',
'Yacuiba',
'Yunchará',
  ),
);
